# Generated by Django 3.0.7 on 2020-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode', '0003_auto_20200615_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='base64_format',
            field=models.FileField(upload_to='base_64'),
        ),
    ]
