# Generated by Django 3.0.7 on 2020-06-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode', '0004_auto_20200615_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='base64_format',
            field=models.FileField(upload_to='Base'),
        ),
    ]
