# Generated by Django 3.0.7 on 2020-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode', '0005_auto_20200615_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='hash_format',
            field=models.CharField(max_length=32),
        ),
    ]
